runtime: nodejs18

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic

env_variables:
  NODE_ENV: "production"
  # Other environment variables will be set via the gcloud command 