[build]
  command = "yarn build"
  publish = "dist/public"
  functions = "netlify/functions"

[dev]
  command = "yarn dev"
  port = 5001
  targetPort = 5001
  publish = "dist/public"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 